[build]
command = "yarn build"
publish = "dist"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18"
GOOGLE_MAPS_API_KEY = "AIzaSyBIP2Zn6M8J58Z0AhQt6qubAfxZBWDYCJg"
[cloudinary]
CLOUDINARY_CLOUD_NAME = "dbfehj6jo"
CLOUDINARY_API_KEY = "583825683527755"
CLOUDINARY_API_SECRET = "OKKh7abDv9_UBieDs-lDi474kjw"

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.

[functions]
directory = "netlify/functions"