[build]
publish = "dist"
command = "yarn build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18"

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.

[functions]
  directory = "netlify/functions"